### ISSUE TITLE
SmartPLUTaskRunner

### ISSUE THREAD

**Issue by mborne** [SimPLU3D/simplu3D-experiments#1]
Générer un fichier "batiment.shp" ou "cuboid.shp" dans le répertoire de sortie (éviter les variables pour faciliter la récupération)

args[0] : dossier en entrée
args[1] : dossier en sortie

**Comment by mbrasebin** [comment]
Done in commit a640c054616598891e2da927f348892633b857a4 

Pour le nom de fichier, le mieux sera de le faire après le script d'agrégation que je te rajouterai quand on aura des résultats (pas très pratique de changer ça pour le moment dans le code de l'IAUIDF car on a besoin de ce nom de fichier pour certains traitements)

**Comment by mbrasebin** [comment]
En bonus, si tu rentres une liste d'ID de parcelle comme argument 3, 4 et suivants, la simulation n'est faite que sur ces parcelles là

**Comment by mbrasebin** [comment]
Mainteanant, il y a besoin de 4 arguments  : 
- Dossier parent /home/mbrasebin/Documents/Donnees/demo-numen/22278/out/ 
- Numéro de sous-dossier 568  
- Dossier de sortie /tmp/tmp/ 
- Fichier de configuration : *.json
